obj-$(CONFIG_AVD_VIRTUAL_DEVICE) += goldfish_address_space.o
obj-$(CONFIG_AVD_VIRTUAL_DEVICE) += goldfish_sync.o
obj-$(CONFIG_AVD_VIRTUAL_DEVICE) += goldfish_pipe.o

KBUILD_CFLAGS += -I$(srctree)/$(src)/../uapi
