# SPDX-License-Identifier: GPL-2.0
ccflags-y := -DCONFIG_ARM_SCMI_TRANSPORT_VIRTIO -DCONFIG_ARM_SCMI_HAVE_TRANSPORT

scmi-bus-y = bus.o
scmi-driver-y = driver.o notify.o
scmi-transport-y += shmem.o
scmi-transport-y += mailbox.o
scmi-transport-y += smc.o
scmi-transport-y += msg.o
scmi-transport-y += virtio.o
scmi-protocols-y = base.o clock.o perf.o power.o reset.o sensors.o system.o voltage.o
scmi-module-objs := $(scmi-bus-y) $(scmi-driver-y) $(scmi-protocols-y) \
		    $(scmi-transport-y)

obj-m += scmi-module.o
obj-m += scmi_pm_domain.o
LINUXINCLUDE := -I$(srctree)/../common-modules/virtual-device/include ${LINUXINCLUDE}
