# SPDX-License-Identifier: GPL-2.0

virtio_video-objs := \
        virtio_video_driver.o \
        virtio_video_device.o \
        virtio_video_vq.o \
        virtio_video_dec.o \
        virtio_video_enc.o \
        virtio_video_caps.o \
        virtio_video_helpers.o

obj-m += virtio_video.o
LINUXINCLUDE := -I$(srctree)/../common-modules/virtual-device/uapi ${LINUXINCLUDE}
